### ISSUE TITLE
Add ability to never spam slam

### ISSUE THREAD

**Issue by mkromerm** [rafaelpimpa/furysim#2]
The auto slam option is great, but I want the option to never spam slam even at full rage. With a 3.4 speed weapon and flurry (2.6s attacks), I don't think its ever worth it to spam slam instead of just doing a normal autoslam.

Spamming slam is 1 slam hit every 1.5 seconds while generating zero rage and spending 15.

Allowing a normal attack cycle with an autoslam at the end is 1 slam hit and 1 white hit in 2.6 seconds. 

I would think that dps would be higher if you just never autoslammed, but I would at least like an option to be able to test that.

**Comment by rafaelpimpa** [comment]
I was doing some tests and yea, looks like not spamming is better! Keep an eye for next release ;)
