### ISSUE TITLE
Autoslam dodge should result in missed auto attack

### ISSUE THREAD

**Issue by mkromerm** [rafaelpimpa/furysim#3]
I found two bugs in one little snippet. First of all, this is from a sim using the slam skill tree but the cast time on slam is still 1.5 seconds.  I think the talent isn't affecting the skill correctly.

Secondly, when performing an autoslam, a dodge on the slam hit itself causes the normal swing to not hit. This is not working correctly in the simulation as in the case below. The mainhand hit at 4.948 should not be able to happen.

3.448  Slam Cast CAST_START (48 rage, 1971 ap)
4.948  Slam SKILL_DODGE (45 rage, 1971 ap)
4.948  Mainhand SWING_HIT for 750 (69 rage, 1971 ap)
4.948  Whirlwind SKILL_HIT for 711 (44 rage, 1971 ap)
6.448  Slam Cast CAST_START (45 rage, 1971 ap)
7.948  Slam SKILL_HIT for 836 (30 rage, 1971 ap)

**Comment by rafaelpimpa** [comment]
Slam cast time is fixed in [this commit](https://github.com/rafaelpimpa/furysim/commit/be692a0bca02dee34fcf40beca5ae44c0a5081d5), I saw it earlier today.

I'm gonna take a look at the dodge bug, I remember testing this before 🤔
