### ISSUE TITLE
[Question] Stat Weights

### ISSUE THREAD

**Issue by furier** [rafaelpimpa/furysim#48]
Hi, love the idea of using your sim to calculate pawn stats.

But I don't fully understand the EAP "constant" as I thought it stood for Equivalent Attack Power or something like that but then how come 8str is rated as 14.4 EAP for me as 8 str is 16 AP? How can I calculate everything vs AP like, 22AP == 1% Crit and so on

**Comment by rafaelpimpa** [comment]
Try to use higher iterations (the higher the best), I usually get 16 EAP for str, since it's calculated based on the itearations samples the results may vary.

It's calculated like this:

```
- DPS_BASE = Avg DPS for default gear
- DPS_AP = Avg DPS for default gear + 50 ap
- DPS_CRIT = Avg DPS for default gear + 1 crit

DPS_EP = 50 / (DPS_AP - DPS_BASE)

Now we multiply this DPS_EP with the difference of each test, e.g:

CRIT_EP = (DPS_CRIT - DPS_BASE) * DPS_EP
```

You can see that it's all based on the avg dps iterations (based on your gear/setup)
