### ISSUE TITLE
Ideas for additional weapons to add.

### ISSUE THREAD

**Issue by robmox** [rafaelpimpa/furysim#5]
Blessed Qiraji Pugio
Felstriker
Glacial Blade
Dreadforge Retaliator
Blackhand Doomsaw
Malowan's Slam
Slavedriver's Cane

**Comment by rafaelpimpa** [comment]
If you're are familiar with Github you can make a pull request for this file: [weapons.json](https://github.com/rafaelpimpa/furysim/blob/master)

**Comment by rafaelpimpa** [comment]
Felstriker proc not implemented yet.
